CALL cinst 7zip
CALL cinst foxitreader
CALL cinst googlechrome
CALL cinst vlc
CALL cinst SublimeText3
CALL cinst dropbox
CALL cinst paint.net
CALL cinst keepass
CALL cinst adblockplusie
CALL cinst adblockpluschrome
